### ISSUE TITLE
Erroneous additional comma in CREATE AGGREGATE

### ISSUE THREAD

**Issue by milgner** [tcdi/pgx#1005]
After implementing an aggregate using the `pg_aggregate` attribute, the following SQL is generated (focussed on the problematic part, leaving out all the working lines):

```
CREATE AGGREGATE datw_integral (
	"start_value" double precision, /* f64 */
,	"range_start" timestamp with time zone, /* pgx::datum::time_stamp_with_timezone::TimestampWithTimeZone */
,	"range_end" timestamp with time zone /* pgx::datum::time_stamp_with_timezone::TimestampWithTimeZone */
	ORDER BY
	"ts" timestamp with time zone, /* pgx::datum::time_stamp_with_timezone::TimestampWithTimeZone */
	"value" double precision /* core::option::Option<f64> */
)
(
	SFUNC = "datw_integral_state", /* re_tools::DatwIntegral::state */
	STYPE = internal, /* pgx::datum::internal::Internal */
	FINALFUNC = "datw_integral_finalize" /* re_tools::DatwIntegral::final */
);
```

as you can see, there are superfluous commas at the beginning of the lines for the second and third arguments. 

Consequently, when trying to install the extension, it yields:

```
ERROR:  syntax error at or near ","
```

I'm not sure whether I'm doing something wrong but when removing these commas and running `CREATE EXTENSION` once more, everything works as expected.

I suspect it has to do with the fact that I'm using multiple input arguments here. I tried replacing the use of `pgx::name!` with unnamed arguments, but the result is the same.

**Comment by eeeebbbbrrrr** [comment]
Which version of pgx are you using, @milgner?

**Comment by milgner** [comment]
It's pgx 0.6.1

**Comment by eeeebbbbrrrr** [comment]
Any chance you can provide your Rust code that causes this to happen?

**Comment by eeeebbbbrrrr** [comment]
@milgner can you provide code that demonstrates this problem?  Without something to reproduce with, I'll be stabbing in the dark and will instead decide to just close this issue.

**Comment by milgner** [comment]
Sorry, forgot about this a bit... I just tried to reproduce it and when it failed, I upgraded my existing project to `0.7.1` and can confirm that the issue has been resolved in that version :+1:

**Comment by eeeebbbbrrrr** [comment]
Amazing!
