### ISSUE TITLE
Changing the API for sound multi-threading

### ISSUE THREAD

**Issue by JelteF** [tcdi/pgx#1079]
From [DESIGN-DECISIONS.md][design], this is the current situation:

> As it relates to any Postgres thing (calling a function, allocated memory, anything at all from pgx::*::*), there is none! Postgres itself is purposely not thread safe and neither is pgx.
>
>It's difficult (right now) to ask the Rust compiler to ensure code is not using pgx from a thread. We have been discussing some ideas. 

[design]: https://github.com/tcdi/pgx/blob/master/DESIGN-DECISIONS.md#thread-safety

The trick suggested here seems pretty nice: https://users.rust-lang.org/t/limit-function-call-only-in-current-thread/58935

It exposes all thread-unsafe functions as methods on a struct, of which an instance can only be created in a single thread.

**Comment by thomcc** [comment]
We don't use the approach you suggest because it would be a pretty invasive and difficult to make change. When I maintained `imgui-rs` that's basically how we did it, and the ergonomics are, honestly, pretty bad.

**Comment by workingjubilee** [comment]
Yeah I can't think of a way to implement that kind of construct which wouldn't make even "build this on one thread and use it from that thread" hard. Given our dynamic checks _do_ manage pretty well, we probably shouldn't torch the crate's ergonomics for the single-thread case to satisfy the multi-threading case.

**Comment by JelteF** [comment]
I didn't realize there were dynamic checks. Those sound fine to me. Thanks for updating the docs.

**Comment by thomcc** [comment]
Yeah, see https://github.com/pgcentralfoundation/pgrx/blob/develop/pgrx-pg-sys/src/submodules/thread_check.rs
