### ISSUE TITLE
Change name to avoid trademark conflicts

### ISSUE THREAD

**Issue by Xof** [tcdi/pgx#1102]
Full disclosure: I'm CEO of, well, PGX Inc.

This is an extremely interesting project and we're looking forward to pointing our clients at it. We do want to mention that "PGX" is a registered trademark of PGX Inc., which is a PostgreSQL consulting company and thus right in this area. We know that it's annoying, but we do ask that you find a different name for the project to avoid confusion. Thanks.

**Comment by eeeebbbbrrrr** [comment]
Would you mind emailing me: e_ridge@tcdi.com. 

Thank you!
