### ISSUE TITLE
Expose tsearch/ts_public.h and tsearch/ts_utils.h

### ISSUE THREAD

**Issue by sachaarbonel** [tcdi/pgx#321]
Hey, thanks for building this great project! It would be nice to bring Rust tokenizers to Postgres. For example, I found this little C extension (quite outdated) that uses those headers [here](https://github.com/i0seph/textsearch_ko/blob/bb476b90dc817164e362822473f30262d508dda5/ts_mecab_ko.c#L395)

**Comment by eeeebbbbrrrr** [comment]
If you want to send us a PR we’ll be happy to merge.
