### ISSUE TITLE
Provide error log output on failed `CREATE EXTENSION` in tests

### ISSUE THREAD

**Issue by JamesGuthrie** [tcdi/pgx#324]
It occasionally happens that I do _something_ to break `CREATE EXTENSION` during development. In these cases, when I run the tests with `cargo pgx test pg14`, I get output something like:

```
error: test failed, to rerun pass '--lib'
      [error] cargo pgx test failed with status = Some(1)
```

In order to debug the actual problem, I have to run `cargo pgx run pg14`, then `CREATE EXTENSION myext;` and _then_ I see whatever the underlying error was which was hit during extension creation.

It would be amazing if we could also get the error log of the failed extension creation in the tests.

**Comment by BradyBonnette** [comment]
@workingjubilee I think we may be able to close this one out as a result of #665 being merged in just now.

I specifically used the example @JamesGuthrie provided (that is, I caused `CREATE EXTENSION` to fail), but 665 also includes outputting other errors that may happen outside of SQL within pgx-tests.
