### ISSUE TITLE
TCDI?

### ISSUE THREAD

**Issue by ccleve** [tcdi/pgx#519]
@eeeebbbbrrrr @Hoverbear 

Could someone explain the move to TCDI?

**Comment by eeeebbbbrrrr** [comment]
Sure.  TCDI (https://www.tcdi.com/) is our employer.

Personally, I have a 24 year history working for them (dating back to 1998).  Back in 2015, I left TCDI to continue development of ZomboDB as open-source.  It was originally developed in-house there and was graciously re-licensed under the Apache v2.

I spent about 6 years developing ZDB as open-source with TCDI's support.  Which then organically led to pgx and pl/rust.

Last year, in 2021, it was time for me to make some life changes so, long story short, I re-joined TCDI and brought on @Hoverbear and a few other strong Rust developers with me to continue pgx, pl/rust, and ZDB development.

So the official "move to TCDI" happened last year and we've finally gotten around to getting things organized and re-branded under the new umbrella.

pgx, pl/rust, and ZDB are critical to TCDI's business goals.  As such, the continued development of these technologies is a major commitment for the company.  It remains my full time job, along with @Hoverbear and now 4 others.

It's great for us to have a company with a 34 year history in business providing the technical, financial, and emotional support we need to keep providing this stuff to the broader Postgres and Rust communities!

**Comment by ccleve** [comment]
Thank you. It sounds like a move to a company that has the financial wherewithal to keep things going is a very good thing.
