### ISSUE TITLE
How to call a Postgres extern function, specifically txid_current_snapshot()

### ISSUE THREAD

**Issue by ccleve** [tcdi/pgx#565]
I need to call txid_current_snapshot() in a couple places in my Rust code, and I'm having a hard time figuring out how to do it.

There are really two questions:

1. I see that
```
#[pg_guard]
extern "C" {
    pub fn txid_current_snapshot(fcinfo: FunctionCallInfo) -> Datum;
}

```
appears in pgx for pg10, 11, and 12, but it has disappeared for pg13 & 14. Is there a reason we shouldn't call it?

2. More generally, how do you call a function that takes a FunctionCallInfo? I'm guessing it has something to do with the function manager (fmgr) and maybe DirectFunctionCall*(), but I'm having a tough time figuring out the syntax. I did find this in fcinfo.rs, line 244:
```
let result = unsafe {
         direct_function_call::<pg_sys::Oid>(
             pg_sys::regclassin,
             vec![ CString::new("pg_class").unwrap().as_c_str().into_datum()]
         )
     };
```
but there is no pg_sys::txid_current_snapshot, plus it appears that direct_function_call() requires at least one parameter, and txid_current_snapshot() does not take a parameter. (**Update**: oops, I see I could just pass in an empty Vec for a no-parameter function.)

I could do this using SPI, but that seems like unnecessary overhead.

**Comment by eeeebbbbrrrr** [comment]
Looks like 13/14 renamed it to `txid_current()`.

That said, to call a Postgres function like this, you need to use `pgx::fcinfo::direct_function_call()`.  The docs are here:  https://docs.rs/pgx/0.4.4/pgx/fcinfo/fn.direct_function_call.html

**Comment by eeeebbbbrrrr** [comment]
> ~~Looks like 13/14 renamed it to `txid_current()`.~~

Looks like 13/14 renamed it to `pg_current_snapshot()`!

**Comment by ccleve** [comment]
Thanks. Looks like pgx doesn't implement the FromDatum trait for the pg_sys::Snapshot or FullTransactionId. This makes it kind of hard because I haven't yet figured out the internal wizardry to implement it myself, or bypass the need for it. For reference, my code looks like this:
```

        let snapshot = unsafe {
            pgx::fcinfo::direct_function_call::<pg_sys::Snapshot>(
                pg_sys::pg_current_snapshot,
                vec![],
            );
        };

```
I may just do this directly in C.

**Comment by ccleve** [comment]
The best way to do this is just to call GetActiveSnapshot() directly in C. Doing that instead.
