### ISSUE TITLE
"dyld[29208]: symbol not found in flat namespace '_PG_exception_stack'" when running tests

### ISSUE THREAD

**Issue by ccleve** [tcdi/pgx#571]
I haven't run tests in a while in my extension, and now I consistently get the error in the title when I do so. When not doing tests, the extension runs fine.

I generated a clean new extension using cargo pgx new, and the test runs fine, so it's something specific in my app. I have not added any new dependencies lately.

I copied the example test code from a newly-generated extension into my extension's lib.rs, and get this:
```

cargo pgx test pg14 test_hello_my_extension
"cargo" "test" "--features" " pg_test" "test_hello_my_extension"
   Compiling relevantdb v0.1.0 (/Users/ccleve/dev/pg/RelevantDB)
    Finished test [unoptimized + debuginfo] target(s) in 12.01s
     Running unittests (target/debug/deps/relevantdb-d337d39059e0ba1e)
dyld[29208]: symbol not found in flat namespace '_PG_exception_stack'
error: test failed, to rerun pass '--lib'

Caused by:
  process didn't exit successfully: `/Users/ccleve/dev/pg/RelevantDB/target/debug/deps/relevantdb-d337d39059e0ba1e test_hello_my_extension` (signal: 6, SIGABRT: process abort signal)

``` 

when I run the test in debug mode in Clion on a Mac, the stack trace looks like this:

```
__abort_with_payload 0x00000001054df82c
abort_with_payload_wrapper_internal 0x00000001054e69ec
abort_with_payload 0x00000001054e6a20
dyld4::halt(char const*) 0x000000010549e91c
dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) 0x0000000105499fb4
start 0x0000000105499068

```

This doesn't tell me much, only that it happens right on startup.

Nothing appears in the Postgres log.

I'm at a loss. Anyone have any clue what this could be?

**Comment by Hoverbear** [comment]
Hi @ccleve, I am guessing you have a test that uses `pgx_pg_sys` code (even indirectly) in a test that is `#[test]` instead of `#[pg_test]`?

(Sorry about the delay, holidays)

**Comment by ccleve** [comment]
@Hoverbear Bingo! Yes, that was it. All happy now.

**Comment by Hoverbear** [comment]
Super glad that's it!
