### ISSUE TITLE
`#[pg_test]` does not respect `#[ignore]` or other test attributes

### ISSUE THREAD

**Issue by workingjubilee** [tcdi/pgx#599]
The `#[ignore]` attribute is not the most common to use in Rust test suites but it is still part of the way the language handles testing and is very convenient when e.g. developing a system that shouldn't have all validation tests applied to it yet, or when some tests should only sometimes be run. ( This can be preferable to diffing over a thousand-line test to "comment it out". )

Currently, annotating something with both `#[pg_test]` and ~~`#[ignore]`~~ most test-related attributes, because it generates a new test with a different name, means that new test is built and run by the PGX framework without attention to the proper results.
Ideally, PGX would respect the annotation.

EDIT: There's more than one attribute it should respect, actually.
- [x] `#[ignore]`
- [x] `#[should_panic]`

**Comment by BradyBonnette** [comment]
@workingjubilee this issue can probably be closed as I merged in #613

**Comment by workingjubilee** [comment]
Yep! I just used `#[should_panic]` in a PL/Rust test last night and it worked like a charm.
