### ISSUE TITLE
Rename `pgx-utils` into something more meaningful, such as `pgx-sqlgen` or equivalent

### ISSUE THREAD

**Issue by BradyBonnette** [tcdi/pgx#655]
Some work was done to remove a lot of dependencies out of the critical build path, as a result of https://github.com/tcdi/pgx/pull/645

Essentially `pgx-utils` was stripped of functionality that really could be implemented other spots. At the end of the day, `pgx-utils` now only contains code that handles internal SQL entities parsing/mappings.

Even though this would be a small refactor, it lends itself to something being named appropriately instead of generically.

**Comment by workingjubilee** [comment]
<joke>`pgx-compiler`</joke>

**Comment by Hoverbear** [comment]
@workingjubilee I think it could be billed as a *trans*piler. :smirk:

**Comment by workingjubilee** [comment]
@eeeebbbbrrrr weighed in and thinks that it might be preferable to keep pgx-utils for another round and try to whittle all of the crate down to nothing, moving components into `pgx-macros`, `cargo-pgx`, and `pgx-pg-sys` as appropriate.
