### ISSUE TITLE
Need pub visibility to SpiHeapTupleDataEntry.type_oid

### ISSUE THREAD

**Issue by montanalow** [tcdi/pgx#688]
My crate issues dynamically generated queries against schemas unknown at compile time. This means we need to handle casting SpiHeapTupleDataEntry's to the correct Rust type at run time. We're currently querying information_schema.columns to get type information, but it would simplify things if we had access to the OID in the query result. Is there a reason SpiHeapTupleDataEntry.type_oid is not `pub`?

**Comment by workingjubilee** [comment]
It's good practice to not make fields public unless the data type is trivial, and I can't off the top of my head evaluate whether that's the case for that type. PR a getter fn?

**Comment by montanalow** [comment]
I believe this field is a u32. 

https://raw.githubusercontent.com/tcdi/pgx/master/pgx-pg-sys/src/pg14.rs line 3233

```
pub type Oid = ::std::os::raw::c_uint;
```

**Comment by workingjubilee** [comment]
Right, I mean that it's not obvious to me that SpiHeapTupleDataEntry is supposed to be trivial and thus have publicly settable members (as `&mut` access to it with `pub` would mean that).
