### ISSUE TITLE
returns with `name!` should display nicely-formatted columns in psql

### ISSUE THREAD

**Issue by ccleve** [tcdi/pgx#713]
Run the "random_values" function in pgx-examples/srf/src/lib.rs

```
select random_values(3);
     random_values      
------------------------
 (1,0.8359141674993014)
 (2,0.2855232692255556)
 (3,0.6648737560575042)
(3 rows)

```
It no longer breaks out the result set into separate "index" and "value" columns. They get mushed together into a set.

I'm using version 4.5. This definitely used to work. I'm not sure which version broke it.

**Comment by workingjubilee** [comment]
Seems to remain an issue on `develop`.

**Comment by workingjubilee** [comment]
@ccleve Can you name the version you are last certain worked?

**Comment by ccleve** [comment]
It looks like it was working in June, and at that point I was still using 0.4.4. 

I tried to check out 0.4.4 to test it, but downgrading cargo pgx is a bit of a headache. I probable should start using docker to get a clean environment when I need it...

**Comment by workingjubilee** [comment]
`cargo install --path cargo-pgx` is the command you are looking for, probably.

**Comment by workingjubilee** [comment]
after
```bash
cargo install --path cargo-pgx
cargo pgx run -p srf
```

I get dropped into psql and
```
srf=# DROP EXTENSION srf; CREATE EXTENSION srf; select srf.random_values(3);
DROP EXTENSION
CREATE EXTENSION
      random_values      
-------------------------
 (1,0.1674659917347202)
 (2,0.8044983269015172)
 (3,0.23902071290598104)
(3 rows)
```

Thus, I seem to get a similar display as far back as `0.4.0`.
Are you sure this is what you used?

**Comment by ccleve** [comment]
I could be wrong, but I'm certain that one particular pg_extern function was working fine, and I first added it when cargo.toml showed that I was using 0.4.3. If you like I'll figure out how to do a full downgrade and test it.

**Comment by ccleve** [comment]
I'm having a hard time downgrading. When I run `cargo install cargo-pgx --version 0.4.3`, it won't compile, because it's pulling pgx-utils version 0.4.5 as a dependency, which is not compatible. The problem is that cargo.toml for pgx 0.4.3 specifies pgx-utils="0.4.3", _not "=0.4.3"_, and it thinks it can use the more recent version. Fortunately, this problem was rectified in the cargo.toml for 0.4.5, but we still can't build anything using 0.4.3. I'll try your `cargo install --path` suggestion.

**Comment by workingjubilee** [comment]
`--locked` is also very helpful. Yes, it is not a default for `cargo install`. No, I don't properly know why.

**Comment by ccleve** [comment]
Ok, it appears that the bug is still there in 0.4.3. I've no idea how it was working back in May or June. Looking at the history of pgx-utils/src/sql_entity_graph/pgextern it looks like there have been no major changes since February. I'm at a loss.

In any case, we have a reproducible error, if not an understanding of when it was introduced. And I do swear it was working at one point.

**Comment by workingjubilee** [comment]
Well, it's not that I don't want to make it display nicely, I just don't have a regression to fix if I can't also bisect the repo to find the non-regressed state.

Yes, I realize this is pedantic.

**Comment by ccleve** [comment]
@workingjubilee Disagree with the name change for this issue. This isn't about formatting. This is about set returning functions returning one column vs the correct number of columns. 

A client needs to see a real table in the result set, not a table with just a single column.

This is definitely a bug, not an enhancement.

**Comment by workingjubilee** [comment]
I mean no slight in rewording it. It just can prove surprisingly easy, while working on PGX, to spend weeks staring into the abyss of the internal binary representations that Postgres uses without even once invoking `psql` and seeing what the function return looks like according to PostgreSQL's text serialization intended for human usage. The rewording is a reminder for myself that a human is asking for this bug to be fixed, not a machine.

**Comment by eeeebbbbrrrr** [comment]
> It no longer breaks out the result set into separate "index" and "value" columns. They get mushed together into a set.


Your SQL is wrong...

You want:  `SELECT * FROM random_values(3)`.  

Your sql is asking postgres to represent a rowtype as a scalar.

**Comment by ccleve** [comment]
>> You want: SELECT * FROM random_values(3).

I cannot believe I made that error. So sorry.
