### ISSUE TITLE
Any reason why PostgresType couldn't be an enum?

### ISSUE THREAD

**Issue by yrashk** [tcdi/pgx#726]
At the moment, it seems one can derive `PostgresType` from struct only, so in cases where I want an enum as a Postgres type, I have to wrap it into a structure and derive from it.

I wonder if there's any reason why this is impossible/undesirable to have this derivation allowed? However, if there's no reason besides lack of interest/prior need, I'd be happy to prepare a PR.

**Comment by yrashk** [comment]
What I am after here is being able to derive `PostgresType` on enum to represent it as a regular (non-enum) type. I have a workaround at the moment that wraps the enum in a struct and that struct derives `PostgresType`. This creates a totally useless type just to work around this limitation.

I can try and do a PR soon on this if there are no material objections?

**Comment by eeeebbbbrrrr** [comment]
PR #828 was just merged.
