### ISSUE TITLE
SQL generation no longer automatic in 0.5?

### ISSUE THREAD

**Issue by mpalmer** [tcdi/pgx#728]
I'm giving `0.5.0-beta.1` a whirl (mostly so I can `#[should_panic]` tests), and all of a sudden my tests don't work at all.  The proximate cause is:

```
     Creating database pgx_tests
thread 'bigint::tests::pg_type_has_operators' panicked at 'There was an issue creating the extension 'pg_enquo' in Postgres:

Caused by:
    ERROR SQLSTATE[42883]: operator does not exist: enquo_bigint < enquo_bigint
    query: CREATE EXTENSION pg_enquo CASCADE;
    params: None
```

Which appears to be caused by the fact that my `pg_enquo-0.0.0.sql` file is no longer being automatically generated and installed.  Back in the "good ol' days" :cowboy_hat_face: of 0.4.5, the output from `cargo pgx test` included this:

```
installing extension                                                                                   
     Copying control file to <...>/share/extension/pg_enquo.control
     Copying shared library to <...>/lib/pg_enquo.so              
 Discovering SQL entities                                                                              
  Discovered 19 SQL entities: 1 schemas (1 unique), 16 functions, 1 types, 0 enums, 0 sqls, 1 ords, 0 hashes, 0 aggregates
     Writing SQL entities to <...>/share/extension/pg_enquo--0.0.0.sql
    Finished installing pg_enquo
```

Now, on the same code but with 0.5.0-beta.1, the corresponding output is a bit shorter:

```
  Installing extension                                                                                 
     Copying control file to <...>/share/extension/pg_enquo.control
     Copying shared library to <...>/lib/pg_enquo.so              
    Finished installing pg_enquo                                                                       
```

(Note the lack of mention of `pg_enquo--0.0.0.sql` now)

I've glanced over the commit messages since 0.4.5, and nothing leapt out at me, and I've followed the guidance in the release notes that say to do `cargo install cargo-pgx --locked --version 0.5.0-beta.1`; for the avoidance of doubt:

```
$ cargo install --locked cargo-pgx --version 0.5.0-beta.1
     Ignored package `cargo-pgx v0.5.0-beta.1` is already installed, use --force to override
```

Have I missed something obvious, is there something missing from the release notes, or have I managed to spawn an honest-to-goodness bug?

**Comment by workingjubilee** [comment]
SQL generation should still be automatic, but an issue regarding ordering operators was found during the refactoring that slipped by the test suite. If you try again with `cargo install cargo-pgx --git https://github.com/tcdi/pgx --branch develop` and override

```toml
[patch.crates.io]
pgx = { git = "https://github.com/tcdi/pgx", branch = "develop" }
```
and that works, then that's the bug.

**Comment by mpalmer** [comment]
Legendary!  That worked.  Got faked out a bit for a minute, because it doesn't mention that it's generating the SQL, but indeed, I now have a working extension again.  I'll close this off, then, and just work off `develop` until a new crate comes out.  Thanks!
