### ISSUE TITLE
AnyElement oid is always zero

### ISSUE THREAD

**Issue by Smittyvb** [tcdi/pgx#735]
I'm trying to upgrade an extension that uses `AnyElement` to the 0.5 beta, and it looks like the `AnyElement::oid` of the type in the `AnyElement` is always zero, when an `AnyElement` is passed in from Postgres. `AnyElement::oid` worked fine in 0.4.5.

Here's a simplified test case with a failing test: https://gist.github.com/Smittyvb/b1ee0bffcf413b85cefe1351caedfaf6

**Comment by workingjubilee** [comment]
I'll try to find out if this can be fixed but if you have FunctionCallInfo you want to break down (a very likely situation for needing AnyElement in the first place) then the workaround for now is to use [`pgx::`~~`get_getarg_type`~~`pg_getarg_type`](https://github.com/tcdi/pgx/pull/738).
