### ISSUE TITLE
Consider making SpinLock methods accessible in PGX

### ISSUE THREAD

**Issue by osawyerr** [tcdi/pgx#752]
The Postgres methods below are not accessible in PGX. Please consider adding them to pgx::pg_sys to make it easier to implement parallel scans in Index Access Methods.

- SpinLockInit
- SpinLockAcquire
- SpinLockRelease

**Comment by osawyerr** [comment]
Do you think this'll make it into 0.5.1? I'm not sure how things are prioritised / scheduled.

**Comment by eeeebbbbrrrr** [comment]
Would you be interested in giving us a PR, @osawyerr?  It's a matter of updating the 5 `.h` files in the `pgx` module.

**Comment by osawyerr** [comment]
I added #includes for storage/spin.h but I don't see the following methods in pgx 0.5.3.

```
#define SpinLockInit(lock) S_INIT_LOCK(lock)
#define SpinLockAcquire(lock) S_LOCK(lock)
#define SpinLockRelease(lock) S_UNLOCK(lock)
#define SpinLockFree(lock)	S_LOCK_FREE(lock)
```

Is there something else I need to do?

**Comment by thomcc** [comment]
Yes, we'd probably need to reimplement those by hand, since they're function-style macros and not callable functions.

**Comment by osawyerr** [comment]
Do you have an example of one that was implemented manually so I can have a look?

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by thomcc** [comment]
Oh, that's pretty reasonable.

**Comment by osawyerr** [comment]
Seeing that implementing this might be fairly involved, I had a question - is it “safe” to use an external process locking library (examples below) as a simple inter-process Mutex in a PGX Index Access Method? e.g
https://github.com/elast0ny/raw_sync-rs
https://lib.rs/crates/named-lock
https://crates.io/crates/proc-lock


Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by thomcc** [comment]
> Seeing that implementing this might be fairly involved

It's not. We merged a fix for this not being exposed into develop in #793. This should be available in the next release (unless that release doesn't contain that PR for whatever reason).

> is it “safe” to use an external process locking library (examples below) as a simple inter-process Mutex in a PGX Index Access Method

Using an external cross-process lock or semaphore is *probably* fine. It might have more overhead, but OTOH also might interact more nicely with the rest of the system (spinning in userspace is often bad).

I suppose @eeeebbbbrrrr would know if there are any caveats specific to this that I'm not aware of (which there may be).

**Comment by thomcc** [comment]
I'm going to close this since we merged a fix for it.
