### ISSUE TITLE
Shared memory and tests

### ISSUE THREAD

**Issue by einarmo** [tcdi/pgx#753]
I ran into some issues when trying to run code that may use shared memory in tests, getting `Can't give out exclusive, lock is in an empty state`, it worked fine when running the extension normally with `cargo pgx run`.

I have two questions/suggestions:

 - I don't really need the shared memory for my tests, so I wanted to just ignore it if the shared memory was uninitialized, but I couldn't figure out how. Would it make sense to have `try_exclusive` and `try_share` methods on `PgLwLock`?
 - Is there any way to initialize the shared memory for tests? I don't really care whether the tests share the memory between them, I just need it to be initialized at all.

**Comment by eeeebbbbrrrr** [comment]
> Is there any way to initialize the shared memory for tests? I don't really care whether the tests share the memory between them, I just need it to be initialized at all.

In order for shared memory to be properly initialized, the extension needs to be loaded by the postmaster, not by each backend connection.

While not a *great* example, take a look at this:  https://github.com/tcdi/pgx/blob/d1ffdb2969f414652d48548341e9d9ff9d02e672/pgx-examples/arrays/src/lib.rs#L103-L114

You can add that block to your code and change the `postgresql_conf_options()` function to return the `postgresql.conf` settings you need to have Postgres load your extension.  Then you should be good to go.
