### ISSUE TITLE
Can't support Windows

### ISSUE THREAD

**Issue by FreeGIS** [tcdi/pgx#771]
`pub fn getpgrp() -> Result<libc::pid_t, i32> {
    |                                  ^^^^^ not found in `libc`

error[E0425]: cannot find function `getpgrp` in crate `libc`
   --> src\lib.rs:141:30
    |
141 |     let res = unsafe { libc::getpgrp() };
    |                              ^^^^^^^ not found in `libc``
when i install pgx in windows had the error, i found the 'fork' can not cross platform,can remove the 'fork' so i can install in windows?

**Comment by eeeebbbbrrrr** [comment]
We don't support Windows and I'm not sure a) we want to, and b) ever will.

None of the pgx developers use Windows and have no way to test everything, let alone continue to make sure it doesn't break over time.
