### ISSUE TITLE
commit ea5b5ed breaks Red Hat derivatives 

### ISSUE THREAD

**Issue by epgts** [tcdi/pgx#778]
[reproduced on centos7, rocky 8, rocky 9]

Commit ea5b5ed broke the build on Red Hat derivative systems.  The previous commit c9a23a1 works.

Since I have Rocky 9 handy, I'll see if I can figure out which part(s) of the block list actually did it.  But if anyone else has suggestsions, I'll take them :).

To reproduce on Rocky 9 (easiest, as it's the most modern of the three):
1. Install prerequisites:
```
  dnf install clang{,-{devel,libs}} openssl-devel redhat-rpm-config
  yum -q -y install https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm
  yum -q -y install postgresql14-devel postgresql14-server

  ./rustup-init.sh -y --no-modify-path --default-toolchain 1.60.0 -c rustfmt
  . ~/.cargo/env
  cargo install --version '=0.5.0' cargo-pgx
  cargo pgx init --pg14 /usr/pgsql-14/bin/pg_config
```

2. `cargo build --features pg14 --no-default-features --package pgx-pg-sys`

Expected:

pgx-pg-sys builds

Actual:
error[E0432]: unresolved import `crate::FlushErrorState`
  --> pgx-pg-sys/src/submodules/guard.rs:12:5
   |
12 | use crate::FlushErrorState;
   |     ^^^^^^^^^^^^^^^^^^^^^^ no `FlushErrorState` in the root

error[E0432]: unresolved import `crate::pg14::AllocSetContextCreateInternal`
   --> pgx-pg-sys/src/lib.rs:656:17
    |
656 |         pub use crate::pg14::AllocSetContextCreateInternal as AllocSetContextCreateExtended;
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `AllocSetContextCreateInternal` in `pg14`

error[E0425]: cannot find value `ERROR` in the crate root
   --> pgx-pg-sys/src/submodules/guard.rs:243:28
    |
243 |                     crate::ERROR as i32,
    |                            ^^^^^ not found in the crate root

error[E0425]: cannot find value `PG_exception_stack` in module `pg_sys`
  --> pgx-pg-sys/src/submodules/setjmp.rs:62:44
   |
62 |         let prev_exception_stack = pg_sys::PG_exception_stack;
   |                                            ^^^^^^^^^^^^^^^^^^ not found in `pg_sys`

error[E0425]: cannot find value `error_context_stack` in module `pg_sys`
  --> pgx-pg-sys/src/submodules/setjmp.rs:63:48
   |
63 |         let prev_error_context_stack = pg_sys::error_context_stack;
   |                                                ^^^^^^^^^^^^^^^^^^^ not found in `pg_sys`

error[E0425]: cannot find value `PG_exception_stack` in module `pg_sys`
  --> pgx-pg-sys/src/submodules/setjmp.rs:69:21
   |
69 |             pg_sys::PG_exception_stack = jump_buffer.as_mut_ptr();
   |                     ^^^^^^^^^^^^^^^^^^ not found in `pg_sys`

error[E0425]: cannot find value `PG_exception_stack` in module `pg_sys`
  --> pgx-pg-sys/src/submodules/setjmp.rs:76:21
   |
76 |             pg_sys::PG_exception_stack = prev_exception_stack;
   |                     ^^^^^^^^^^^^^^^^^^ not found in `pg_sys`

error[E0425]: cannot find value `error_context_stack` in module `pg_sys`
  --> pgx-pg-sys/src/submodules/setjmp.rs:77:21
   |
77 |             pg_sys::error_context_stack = prev_error_context_stack;
   |                     ^^^^^^^^^^^^^^^^^^^ not found in `pg_sys`

error[E0425]: cannot find value `PG_exception_stack` in module `pg_sys`
  --> pgx-pg-sys/src/submodules/setjmp.rs:83:17
   |
83 |         pg_sys::PG_exception_stack = prev_exception_stack;
   |                 ^^^^^^^^^^^^^^^^^^ not found in `pg_sys`

error[E0425]: cannot find value `error_context_stack` in module `pg_sys`
  --> pgx-pg-sys/src/submodules/setjmp.rs:84:17
   |
84 |         pg_sys::error_context_stack = prev_error_context_stack;
   |                 ^^^^^^^^^^^^^^^^^^^ not found in `pg_sys`

error[E0412]: cannot find type `BOX` in the crate root
  --> pgx-pg-sys/src/submodules/sql_translatable.rs:51:40
   |
51 | unsafe impl SqlTranslatable for crate::BOX {
   |                                        ^^^ not found in the crate root

error[E0412]: cannot find type `Point` in the crate root
  --> pgx-pg-sys/src/submodules/sql_translatable.rs:60:40
   |
60 | unsafe impl SqlTranslatable for crate::Point {
   |                                        ^^^^^ not found in the crate root

error[E0412]: cannot find type `sigjmp_buf` in the crate root
  --> pgx-pg-sys/src/submodules/mod.rs:35:26
   |
35 |         env: *mut crate::sigjmp_buf,
   |                          ^^^^^^^^^^ not found in the crate root

error[E0425]: cannot find function `pfree` in the crate root
   --> pgx-pg-sys/src/lib.rs:185:16
    |
185 |         crate::pfree(node_to_string as *mut std::ffi::c_void);
    |                ^^^^^ not found in the crate root

error[E0425]: cannot find function `palloc0` in the crate root
   --> pgx-pg-sys/src/lib.rs:199:39
    |
199 |         let pg_cstr = unsafe { crate::palloc0(self_bytes.len() + 1) as *mut std::os::raw::c_uchar };
    |                                       ^^^^^^^ not found in the crate root

Some errors have detailed explanations: E0412, E0425, E0432.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `pgx-pg-sys` due to 15 previous errors

**Comment by Smittyvb** [comment]
This has been fixed in `develop` by #760.

**Comment by thomcc** [comment]
This is a known issue and we're looking into it. The build on the `develop` branch has a fix (https://github.com/tcdi/pgx/commit/d5fb78fa3674e81654bdf5a5c584f214d9b71916) which will be included in the next release (or a more proper fix for the same issue, possibly).

Thanks for the info though, it wasn't clear that this was an issue on all redhat-based systems, that really helps.

**Comment by epgts** [comment]
Thanks @Smittyvb and @thomcc !

Can you expedite a 0.5 patch release?  Failure to build is quite the regression :)

Along with PR #776 too - that was the next failure I hit after grabbing the #760 fix.

Thanks!

**Comment by workingjubilee** [comment]
Please try
```toml
pgx = "0.5.3"
```
in your Cargo.toml and confirm if this is fixed, thank you!

**Comment by epgts** [comment]
@workingjubilee All clear on centos 7!  Thanks!

**Comment by epgts** [comment]
For the avoidance of doubt:  0.5.3 is working for us on Rocky 8 as well.

Again, thanks!

**Comment by workingjubilee** [comment]
Excellent!
