### ISSUE TITLE
cargo pgx run pg13，fatal error: 'tr1/cstdarg' file not found

### ISSUE THREAD

**Issue by wonb168** [tcdi/pgx#783]
clang -v https://github.com/tcdi/pgx/pull/5.0.1
gcc -v https://github.com/tcdi/pgx/issues/7.3.0
pgx : newest
when cargo pgx run pg13:

thread 'main' panicked at 'Unable to generate bindings for pg13: ClangDiagnostic("/usr/include/stdarg.h:32:10: fatal error: 'tr1/cstdarg' file not found\n")', /home/wcz/.cargo/registry/src/github.com-1ecc6299db9ec823/pgx-pg-sys-0.5.0/build.rs:563:13

**Comment by BradyBonnette** [comment]
Hi,

What OS/distro are you using?

**Comment by wonb168** [comment]
centos7

**Comment by thomcc** [comment]
This is a duplicate of #778 then, which should be fixed in the next release.

**Comment by eeeebbbbrrrr** [comment]
Yep. Closing.
