### ISSUE TITLE
Interference between multiple open SpiTupleTable

### ISSUE THREAD

**Issue by EdMcBane** [tcdi/pgx#936]
Once a `SpiTupleTable` has been opened via e.g. `SpiClient::select`, opening a new one "overwrites" the effective size of the first one; although `SpiTupleTable::len` returns the correct value, accessing the tuples via `SpiTupleTable::next`, `SpiTupleTable::get_datum` behaves improperly. E.g.

```rust
Spi::execute(|client| {
    let a = client.select("SELECT 1", None, None).first();
    let _b = client.select("SELECT 1 WHERE 'f'", None, None);
    // len() and is_empty() behave correctly
    assert!(!a.is_empty());
    assert_eq!(1, a.len());
    // but accessing the data behaves as if the table is empty
    assert!(a.get_heap_tuple().is_some()); // fails
    assert_eq!(Some(1), a.get_datum(1)); // fails
});
```

The reason is `SpiTupleTable::get_datum` and `SpiTupleTable::get_heap_tuple` rely on the static `pg_sys::SPI_processed` for size instead of the value copied at construction in `self.size`.

**Comment by yrashk** [comment]
Should we close this one since it was fixed in #938?
