### ISSUE TITLE
No longer getting context for errors

### ISSUE THREAD

**Issue by ccleve** [tcdi/pgx#978]
I just upgraded from 0.5.6 to 0.6.1. In the old version, I would see errors like this:

```
psql:scripts/test_create.sql:53: ERROR:  not yet implemented
CONTEXT:  src/query/node_enums/node.rs:41:17
```

In the new version, the CONTEXT line is gone.

I see you considered context in #834. 

Is there a way to turn the context back on?

(To reproduce the error, just put a todo!() in your code and execute it.)

**Comment by eeeebbbbrrrr** [comment]
you can ask psql for `\errverbose` to get it as the "LOCATION" line.  Or you can twiddle `log_error_verbosity` in postgresql.conf to your liking to get more information.

We actually don't emit the "CONTEXT" line anymore as that now goes to LOCATION.  0.6.x supports DETAIL, and in the develop branch we also support HINT.  

I'm reserving CONTEXT for when an idea comes to mind where pgx might can build up a more robust backtrace above and beyond the LOCATION line.
