### ISSUE TITLE
Can you consider supporting the win platform

### ISSUE THREAD

**Issue by PaiGack** [tcdi/pgx#999]

**Comment by eeeebbbbrrrr** [comment]
As the world exists today, Jan 6 2023, we have no plans of supporting Windows.  Without going into details, as they'll just sound like excuses, the project lacks the necessary resources to develop and maintain support for a platform that's as far removed from POSIX as Windows.

You saw some of that with issue #997.

There are also business/corporate concerns around pgx and again, as of today, Windows is not one of them.

However... if someone (perhaps you?) were to engage us with a plan to support Windows **and** provide a relatively small and as-non-invasive-as-possible pull request, we would **seriously** consider merging and maintaining it.  

The core pgx development team would then need to figure out logistics around testing, CI, code maintenance, and also invest in some hardware and software licenses.

Windows support is not a small ask, so we have to ask the user community to help us do it... mainly by doing most of the heavy lifting.

The world could change tomorrow, but right now, Windows support isn't on our radar.

Barring that, pgx is known to work just fine under WSL2, and I'd recommend you, and anyone looking for Windows support in the short term, to give that a try.  It'll necessitate also running Postgres in the WSL2 environment, but my understanding is that WSL2 is really good nowadays.

Thanks for understanding!

eric
